# 作業 : (Kaggle)鐵達尼生存預測
***
- 分數以網站評分結果為準, 請同學實際將提交檔(*.csv)上傳試試看  
https://www.kaggle.com/c/titanic/submit

# [作業目標]
- 試著模仿範例寫法, 在鐵達尼生存預測中, 觀察觀查混合泛化 (Blending) 的寫法與效果

# [作業重點]
- 觀察混合泛化的準確度 (In[14]), 是否比單一模型準確度為高 (In[11~13])  
- 除了我們的權重, 同學也可以試著自行調整權重 (注意:權重和=1), 看看有什麼影響
- Hint : 除了權重, 分類預測的調整, 還可以調整什麼地方?

In [1]:
# 做完特徵工程前的所有準備 (與前範例相同)
import pandas as pd
import numpy as np
import copy, time
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

data_path = 'data/'
df_train = pd.read_csv(data_path + 'titanic_train.csv')
df_test = pd.read_csv(data_path + 'titanic_test.csv')

train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()

Pclass                                                 Name     Sex   Age  \
0       3                              Braund, Mr. Owen Harris    male  22.0   
1       1  Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0   
2       3                               Heikkinen, Miss. Laina  female  26.0   
3       1         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4       3                             Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket     Fare Cabin Embarked  
0      1      0         A/5 21171   7.2500   NaN        S  
1      1      0          PC 17599  71.2833   C85        C  
2      0      0  STON/O2. 3101282   7.9250   NaN        S  
3      1      0            113803  53.1000  C123        S  
4      0      0            373450   8.0500   NaN        S

In [2]:
# 檢查 DataFrame 空缺值的狀態
def na_check(df_data):
    data_na = (df_data.isnull().sum() / len(df_data)) * 100
    data_na = data_na.drop(data_na[data_na == 0].index).sort_values(ascending=False)
    missing_data = pd.DataFrame({'Missing Ratio' :data_na})
    display(missing_data.head(10))
na_check(df)

Missing Ratio
Cabin         77.463713
Age           20.091673
Embarked       0.152788
Fare           0.076394

In [3]:
# 以下 In[3]~In[10] 只是鐵達尼預測中的一組特徵工程, 並以此組特徵工程跑參數, 若更換其他特徵工程, In[10]的參數需要重新跑
# Sex : 直接轉男 0 女 1
df["Sex"] = df["Sex"].map({"male": 0, "female":1})
# Fare : 用 log 去偏態, 0 則直接取 0
df["Fare"] = df["Fare"].map(lambda i: np.log(i) if i > 0 else 0)
# Age : 缺值用中位數補
df["Age"] = df["Age"].fillna(df['Age'].median())

In [4]:
# Title 的 特徵工程 : 將各種頭銜按照類型分類, 最後取 One Hot
df_title = [i.split(",")[1].split(".")[0].strip() for i in df["Name"]]
df["Title"] = pd.Series(df_title)
df["Title"] = df["Title"].replace(['Lady', 'the Countess','Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
df["Title"] = df["Title"].map({"Master":0, "Miss":1, "Ms" : 1 , "Mme":1, "Mlle":1, "Mrs":1, "Mr":2, "Rare":3})
df["Title"] = df["Title"].astype(int)
df = pd.get_dummies(df, columns = ["Title"])

In [5]:
# 新建:家庭大小 (Fsize)特徵, 並依照大小分別建獨立欄位
df["Fsize"] = df["SibSp"] + df["Parch"] + 1
df['Single'] = df['Fsize'].map(lambda s: 1 if s == 1 else 0)
df['SmallF'] = df['Fsize'].map(lambda s: 1 if  s == 2  else 0)
df['MedF'] = df['Fsize'].map(lambda s: 1 if 3 <= s <= 4 else 0)
df['LargeF'] = df['Fsize'].map(lambda s: 1 if s >= 5 else 0)

In [6]:
# Ticket : 如果不只是數字-取第一個空白之前的字串(去除'.'與'/'), 如果只是數字-設為'X', 最後再取 One Hot
Ticket = []
for i in list(df.Ticket):
    if not i.isdigit() :
        Ticket.append(i.replace(".","").replace("/","").strip().split(' ')[0])
    else:
        Ticket.append("X")        
df["Ticket"] = Ticket
df = pd.get_dummies(df, columns = ["Ticket"], prefix="T")

In [7]:
# Cabib 依照第一碼分類, 再取 One Hot
df["Cabin"] = pd.Series([i[0] if not pd.isnull(i) else 'X' for i in df['Cabin'] ])
df = pd.get_dummies(df, columns = ["Cabin"], prefix="Cabin")

In [8]:
# Embarked, Pclass 取 One Hot
df = pd.get_dummies(df, columns = ["Embarked"], prefix="Em")
df["Pclass"] = df["Pclass"].astype("category")
df = pd.get_dummies(df, columns = ["Pclass"], prefix="Pc")

# 捨棄 Name 欄位
df.drop(labels = ["Name"], axis = 1, inplace = True)

In [9]:
# 確認缺值 與 目前的資料表內容
na_check(df)
df.head()

Empty DataFrame
Columns: [Missing Ratio]
Index: []

Sex   Age  SibSp  Parch      Fare  Title_0  Title_1  Title_2  Title_3  \
0    0  22.0      1      0  1.981001        0        0        1        0   
1    1  38.0      1      0  4.266662        0        1        0        0   
2    1  26.0      0      0  2.070022        0        1        0        0   
3    1  35.0      1      0  3.972177        0        1        0        0   
4    0  35.0      0      0  2.085672        0        0        1        0   

   Fsize  Single  SmallF  MedF  LargeF  T_A  T_A4  T_A5  T_AQ3  T_AQ4  T_AS  \
0      2       0       1     0       0    0     0     1      0      0     0   
1      2       0       1     0       0    0     0     0      0      0     0   
2      1       1       0     0       0    0     0     0      0      0     0   
3      2       0       1     0       0    0     0     0      0      0     0   
4      1       1       0     0       0    0     0     0      0      0     0   

   T_C  T_CA  T_CASOTON  T_FC  T_FCC  T_Fa  T_LINE  T_LP  T_PC  T_PP  T_PPP  \
0    0     0          0     0      0     0       0     0     0     0      0   
1    0     0          0     0      0     0       0     0     1     0      0   
2    0     0          0     0      0     0       0     0     0     0      0   
3    0     0          0     0      0     0       0     0     0     0      0   
4    0     0          0     0      0     0       0     0     0     0      0   

   T_SC  T_SCA3  T_SCA4  T_SCAH  T_SCOW  T_SCPARIS  T_SCParis  T_SOC  T_SOP  \
0     0       0       0       0       0          0          0      0      0   
1     0       0       0       0       0          0          0      0      0   
2     0       0       0       0       0          0          0      0      0   
3     0       0       0       0       0          0          0      0      0   
4     0       0       0       0       0          0          0      0      0   

   T_SOPP  T_SOTONO2  T_SOTONOQ  T_SP  T_STONO  T_STONO2  T_STONOQ  T_SWPP  \
0       0          0          0     0        0         0         0       0   
1       0          0          0     0        0         0         0       0   
2       0          0          0     0        0         1         0       0   
3       0          0          0     0        0         0         0       0   
4       0          0          0     0        0         0         0       0   

   T_WC  T_WEP  T_X  Cabin_A  Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  \
0     0      0    0        0        0        0        0        0        0   
1     0      0    0        0        0        1        0        0        0   
2     0      0    0        0        0        0        0        0        0   
3     0      0    1        0        0        1        0        0        0   
4     0      0    1        0        0        0        0        0        0   

   Cabin_G  Cabin_T  Cabin_X  Em_C  Em_Q  Em_S  Pc_1  Pc_2  Pc_3  
0        0        0        1     0     0     1     0     0     1  
1        0        0        0     1     0     0     1     0     0  
2        0        0        1     0     0     1     0     0     1  
3        0        0        0     0     0     1     1     0     0  
4        0        0        1     0     0     1     0     0     1

In [10]:
# 將資料最大最小化
df = MinMaxScaler().fit_transform(df)

# 將前述轉換完畢資料 df , 重新切成 train_X, test_X
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

# 使用三種模型 : 邏輯斯迴歸 / 梯度提升機 / 隨機森林, 參數使用 Random Search 尋找
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
lr = LogisticRegression(tol=0.001, penalty='l2', fit_intercept=True, C=1.0)
gdbt = GradientBoostingClassifier(tol=100, subsample=0.75, n_estimators=250, max_features=20,
                                  max_depth=6, learning_rate=0.03)
rf = RandomForestClassifier(n_estimators=100, min_samples_split=2, min_samples_leaf=1, 
                            max_features='sqrt', max_depth=6, bootstrap=True)

In [64]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(train_X, train_Y, test_size=0.25, random_state=42)


In [69]:
# 線性迴歸預測檔 (結果有部分隨機, 請以 Kaggle 計算的得分為準, 以下模型同理)
lr.fit(x_train, y_train)
lr_pred_train_proba = lr.predict_proba(x_train)[:,1]
lr_pred_train = [1 if i >=0.47114150179855546 else 0 for i in lr_pred_train_proba]
lr_pred_val_proba = lr.predict_proba(x_val)[:,1]
lr_pred_val = [1 if i >=0.47114150179855546 else 0 for i in lr_pred_val_proba]
print(metrics.accuracy_score(y_train, lr_pred_train),metrics.accuracy_score(y_val, lr_pred_val))

0.8458083832335329 0.820627802690583


In [70]:
lr_pred = lr.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': lr_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.47114150179855546 else 0) 
sub.to_csv('titanic_lr.csv', index=False) 

In [50]:
# 梯度提升機預測檔 
gdbt.fit(train_X, train_Y)
gdbt_pred = gdbt.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': gdbt_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_gdbt.csv', index=False)

In [51]:
# 隨機森林預測檔
rf.fit(train_X, train_Y)
rf_pred = rf.predict_proba(test_X)[:,1]
sub = pd.DataFrame({'PassengerId': ids, 'Survived': rf_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_rf.csv', index=False)

# 作業
* 雖然同樣是混合泛化，分類預測其實與回歸預測有相當多的差異性，
因為鐵達尼預測的結果是 '生存/死亡'，輸出不是 0 就是 1  
因此要用權重混合時，需要以以機率的形式混合，因此我們在作業前幾格當中，先幫各位同學把預測值寫成了機率的形式  
(請同學把下列程式完成，並將結果提交到 Kaggle 網站看看結果)

* 但是光是這樣，分類問題的混合泛化就能比單模預測還要好嗎?  
已經快要期中考了，這裡請同學挑戰看看，還有沒有什麼方法可以改進混合泛化的結果?

In [46]:
gdbt_pred_train = gdbt.predict_proba(train_X)[:,1]
gdbt_pred_train.sort()

In [43]:
print(train_Y.sum(),train_Y.count(),train_Y.sum()/train_Y.count() )

342 891 0.3838383838383838


In [47]:
gdbt_pred_train[-342]

0.3997429552842237

In [59]:
lr_pred_train = lr.predict_proba(train_X)[:,1]
gdbt_pred_train = gdbt.predict_proba(train_X)[:,1]
rf_pred_train = rf.predict_proba(train_X)[:,1]

In [17]:
np.percentile(lr_pred_train,[0.25,0.5,0.75])

array([0.00531741, 0.00780795, 0.00973455])

In [16]:
from sklearn import metrics

In [33]:
metrics.accuracy_score(train_Y,[1 if i >=0.47114150179855546 else 0 for i in lr_pred_train])

0.8383838383838383

In [61]:
metrics.accuracy_score(train_Y,[1 if i >=0.3838383838383838 else 0 for i in gdbt_pred_train])

0.9539842873176206

In [35]:
metrics.accuracy_score(train_Y,[1 if i >=0.47114150179855546 else 0 for i in rf_pred_train])

0.8540965207631874

In [15]:
lr_pred_train[:10]

array([0.04863713, 0.91409784, 0.62097388, 0.8926081 , 0.06211915,
       0.09256879, 0.53117589, 0.20206167, 0.63441432, 0.88780195])

In [48]:
# 混合泛化預測檔 
"""
Your Code Here
"""
blending_pred = lr_pred*0.2  + gdbt_pred*0.6 + rf_pred*0.2
sub = pd.DataFrame({'PassengerId': ids, 'Survived': blending_pred})
# sub['Survived'] =  [1 if i >=0.47114150179855546 else 0 for i in blending_pred]

sub['Survived'] =  [1 if i >=0.3997429552842237 else 0 for i in gdbt_pred]
sub.to_csv('titanic_blending.csv', index=False)

In [38]:
# sub.head()

In [53]:
train_X[0]

array([0.        , 0.27345609, 0.125     , 0.        , 0.31752073,
       0.        , 0.        , 1.        , 0.        , 0.1       ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       1.        ])