## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [10]:
# 讀取糖尿病資料集
boston = datasets.load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(StandardScaler().fit_transform(boston.data), boston.target, test_size=0.2, random_state=4)


In [8]:
MinMaxScaler().fit_transform(x_train)[0]

array([9.02777434e-04, 4.50000000e-01, 1.00000000e-01, 0.00000000e+00,
       1.06995885e-01, 6.93044645e-01, 2.40988671e-01, 4.86518928e-01,
       1.73913043e-01, 4.02671756e-01, 2.76595745e-01, 9.83836805e-01,
       3.14569536e-02])

In [9]:
StandardScaler().fit_transform(x_train)[0]

array([-0.42744775,  1.48401136, -1.11423904, -0.25683275, -1.02191526,
        1.27327666, -1.51790301,  1.26245222, -0.54325496, -0.08885599,
       -1.50968688,  0.36523284, -1.37446434])

In [12]:
# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = regr.predict(x_test)

In [13]:
print(regr.coef_)

[-0.99650452  1.09798223  0.05660913  0.82061615 -1.93169153  2.72634181
 -0.30644738 -3.24231272  2.55051678 -2.25716447 -1.96014262  0.80335156
 -3.26540267]


In [14]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.42


In [16]:
# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=1.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = lasso.predict(x_test)

# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_


array([-0.        ,  0.        , -0.        ,  0.        , -0.        ,
        2.76927106, -0.        , -0.        , -0.        , -0.11184766,
       -1.34573317,  0.05884209, -3.26223471])

In [17]:

# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 33.84


In [27]:
# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=10.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進模型得到預測結果
y_pred = ridge.predict(x_test)

In [28]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
print(ridge.coef_)

[-0.90367102  0.91945019 -0.17090499  0.84008604 -1.65633447  2.78124575
 -0.30734687 -2.90737116  1.88386322 -1.62920452 -1.8910977   0.78692635
 -3.16784328]


In [29]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.76
